valor_inicial = input('Ingrese valor numerico inicial:    ')
valor_final = input('Ingrese valor numerico final:     ')
salto = input('ingrese el salto:       ')
secuencia = range(valor_inicial, valor_final, salto)
print(secuencia)
